### PR TITLE
adds new methods like `toCamel` that accept aribtrary data structures

### LINKED ISSUE #1: [Feature request] export methods that work with any kind of data
What do you think about exporting a method that you can pass any kind of data (object, array, string, number, ...) and it will automatically determine the right thing to do.

Something like:
```
function camelize (data, options) {
  if (isArray(data)) {
    return camelArray(data, options)
  } else if (isObject(data)) {
    return camelKeys(data, options)
  } else {
    return data
  }
}
```

Would that be something that you would consider adding to the library?

### PR DESCRIPTION
**Pull request by jhilden**
fixes #1 

What do you think?

### CODE REVIEW

**Comment by jhilden** [comment]
Alternative naming suggestions, in case you don't like `.toCamel`:
* `.camelArbitrary`
* `.camelData`
* `.camelAny`

**Comment by tuvistavie** [comment]
`toCamel` sounds good, thank you very much for the PR.

**Comment by jhilden** [comment]
Thanks a lot for the merge.  Will you release a new version to npm soon?

**Comment by tuvistavie** [comment]
Just published 0.2.0
Thanks for the help :smile:

**Pull request merged**
